### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by majewsky** [sapcc/keppel#1]
This may be split out into multiple issues at some point. For now, let's keep the ceremony to a minimum.

- functionality
    - [x] MVP: `docker pull/push` works for authenticated users
    - [x] [`GET /v2/_catalog`](https://github.com/docker/distribution/blob/master/docs/spec/api.md#listing-repositories)
    - [x] orchestrate registry fleet via k8s (connect objects with annotations for reliable cleanup)
    - [ ] allow account deletion (similar to swift-account-reaper: mark account as deleted, delete from DB only after all data has been purged by a background job)
    - [x] repository RBAC (enable `docker pull/push` for unauthenticated users)
    - [ ] federation
- code quality
    - [x] automated tests
      - [x] Keppel v1 API
      - [x] Registry v2 API
      - [x] auth API
    - [x] automatically run golint/govet/gofmt
    - [ ] resolve all of `rg TODO pkg`
- release quality
    - [ ] Prometheus metrics
    - [x] API spec for the `/keppel/` parts
    - [x] install documentation (explain config options in more detail)
    - [ ] operator handbook for recurring actions (issuer cert rotation)

**Comment by majewsky** [comment]
This is all done by now.
